# support 256 colors
export TERM=xterm-256color

# resume downloads if dc'd
alias wget='wget -c'
alias google='google-chrome'
alias files='xdg-open .'
alias term='gnome-terminal'
alias gdb='gdb -q -ex r'
alias tree='tree -C'

# some more ls aliases
alias l='ls'
alias la='ls -A'
alias ll='ls -Alh'
alias lt='ls -Alhtr'

# easy zsh move
autoload -U zmv
alias mmv='noglob zmv -W'

alias sl='sl'

# sudo uses aliases
# alias sudo='sudo '

function say() {
    if which cowsay >/dev/null; then
        cowfile=`ls /usr/share/cowsay/cows | sort -R | tail -1`
        cowsay -f $cowfile "$@"
        # cowsay -f head-in -e "><" "$@" | cowthink -n -f dragon-and-cow -e "OO" | cowthink -n -s -f bong
    else
        echo $@
    fi
}

alias bored='while :; do quote && sleep 4; done'
alias lol='say lol'
alias yo='say yo-yo'
alias hey='say oh hai'
alias fart='say pffttbbttbt'

# more dots
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias size='command du -sh'
alias count='wc -l'

alias shutdown='quote && sudo shutdown -h now'
alias reboot='sudo shutdown -r now'
alias logout='gnome-session-quit'

# pipe to grep
alias -g '@'="| command grep"
alias pgrep="ps -e | command grep"
alias dgrep="dpkg -l | command grep"

# add to clipboard
alias clip="xclip -sel clip"

# ls after every cd
function chpwd() {
    emulate -LR zsh
    ls
}

# quick clone
function gclone()
{
    if [ "$#" -eq 0 ]; then
        say "Enter a path!"
        return
    fi
    local gitpath=git@github.com:"$1".git
    shift
    git clone $gitpath "$@"
}
